### ISSUE TITLE
Using envs makes a mistake when import emd. 

### ISSUE THREAD

**Issue by GuanlinLee** [yunlu-chen/PointMixup#11]
I am using pytroch-1.8.1, cuda-10.1 and python 3.6.
After compiling the emd, I import torch and emd. However, an error occurs:

ImportError: /root/anaconda3/envs/pc/lib/python3.6/site-packages/emd-0.0.0-py3.6-linux-x86_64.egg/emd.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor4sizeEl

**Comment by GuanlinLee** [comment]
For a pytorch=1.2.0, here is another error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by GuanlinLee** [comment]
After recreating an env in conda, I can import emd without errors. However, I have  a Segmentation fault as follow:

Fatal Python error: Segmentation fault

Thread 0x00007f9fe2ffd700 (most recent call first):
  File "/root/anaconda3/envs/gl/lib/python3.6/threading.py", line 295 in wait
  File "/root/anaconda3/envs/gl/lib/python3.6/queue.py", line 164 in get
  File "/root/anaconda3/envs/gl/lib/python3.6/site-packages/tensorflow/python/summary/writer/event_file_writer.py", line 159 in run
  File "/root/anaconda3/envs/gl/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/root/anaconda3/envs/gl/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007f9fe37fe700 (most recent call first):
  File "/root/anaconda3/envs/gl/lib/python3.6/threading.py", line 295 in wait
  File "/root/anaconda3/envs/gl/lib/python3.6/queue.py", line 164 in get
  File "/root/anaconda3/envs/gl/lib/python3.6/site-packages/tensorflow/python/summary/writer/event_file_writer.py", line 159 in run
  File "/root/anaconda3/envs/gl/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/root/anaconda3/envs/gl/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x00007fa2ff138740 (most recent call first):
  File "/root/point_cloud/net/emd_module.py", line 58 in forward
  File "/root/point_cloud/net/emd_module.py", line 79 in forward
  File "/root/anaconda3/envs/gl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547 in __call__
  File "train.py", line 250 in train_one_epoch
  File "train.py", line 190 in train
  File "train.py", line 345 in <module>
Segmentation fault

**Comment by GuanlinLee** [comment]
When I try to use emd_moudle.py to run test_emd(), there is also a segmentation fault.

**Comment by GuanlinLee** [comment]
It has been solved by updating my gcc to gcc7.
Thanks for your excellent work!
