### ISSUE TITLE
How to Install?

### ISSUE THREAD

**Issue by liang3588** [yunlu-chen/PointMixup#13]
When I apply "sh setup.sh", the following error will appear.
“
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    "nvcc": ["-O2", "-I{}".format("{}/include".format(_ext_src_root))],
  File "/public/data1/users/liangyaqian/.conda/envs/pytorch-3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 867, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/public/data1/users/liangyaqian/.conda/envs/pytorch-3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 975, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/public/data1/users/liangyaqian/.conda/envs/pytorch-3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1982, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    'emd/emd_cuda.cu',
  File "/public/data1/users/liangyaqian/.conda/envs/pytorch-3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 867, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/public/data1/users/liangyaqian/.conda/envs/pytorch-3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 975, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/public/data1/users/liangyaqian/.conda/envs/pytorch-3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1982, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
setup.sh: line 8: cd: cd: No such file or directory
”
How should I solve this problem?

**Comment by yunlu-chen** [comment]
Hi,

You will need to set CUDA_HOME environment variable as the folder your cuda is installed.
